services:
  - type: web
    name: Drone
    env: python
    buildCommand: |
      apt-get install -y git python3 python3-pip && \
      pip install -r requirements.txt
    startCommand: python -m main
