services:
  - type: web
    name: SR
    env: python3
    buildCommand: |
      apt-get install -y git python3 python3-pip && \
      pip install -r requirements.txt
    startCommand: |
      python3 -m app && \
      python3 -m main
