services:
  - type: web
    name: my-web-service
    env: python
    plan: free
    buildCommand: |
      apt-get install -y git python3 python3-pip && \
      pip install -r requirements.txt
    startCommand: python main.py
